# 配置服务端口号
server:
  port: 8821

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_farm?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "010923"
  # Redis的相关配置
  data:
    redis:
      host: 192.168.200.131
      port: 6379

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
farm:
  minio:
    endpointUrl: http://192.168.200.131:9000
    accessKey: minioadmin
    secreKey: minioadmin
    bucketName: farm-produce