server:
  port: 8831

spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_farm?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "010923"
  # Redis的相关配置
  data:
    redis:
      host: 192.168.200.131
      port: 6379
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
