server:
  port: 8871

spring:
  application:
    name: service-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_farm?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "010923"
  data:
    redis:
      host: 192.168.200.130
      port: 6379

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml